# Generated by Django 3.0.2 on 2020-01-31 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_auto_20200131_0226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='date_added_entry',
            new_name='date_added',
        ),
    ]
